from typing import TypedDict, List, Optional, Dict, Any


class SwarmState(TypedDict):
    """
    Shared state that all agents can read and write.
    This is the 'memory' of the swarm — each agent reads it and returns partial updates.
    """
    # Core data
    messages: List[dict]          # Conversation / reasoning history
    event_context: dict           # Current event info (name, date, venue, description)

    # Schedule data (top-level for easy agent access)
    sessions: List[dict]          # Sessions list (flat, for agents to read directly)
    rooms: List[dict]             # Rooms list (flat)
    speakers: List[dict]          # Speakers list (flat)
    schedule_changes: List[dict]  # Pending schedule change actions from crisis agent

    # Agent-specific data
    schedule: Optional[dict]      # Nested schedule state (legacy / scheduler output)
    participants: Optional[List[dict]]  # Loaded participant list
    email_queue: List[dict]       # Pending emails to send
    emails_sent: int              # How many emails were actually sent
    social_queue: List[dict]      # Pending social posts
    generated_posts: List[dict]   # Social posts generated by content agent

    # Crisis handling
    active_crisis: Optional[dict]      # Current crisis being resolved
    crisis_resolution: Optional[dict]  # Resolution plan from crisis agent

    # Graph routing
    next_agent: Optional[str]     # Which agent to call next (scheduler, email, crisis, content)
    workflow_complete: bool        # Is the workflow finished?

    # Observability
    agent_logs: List[str]         # Timestamped agent activity for UI display


def make_initial_state(
    workflow_type: str,
    event_context: dict = None,
    schedule: dict = None,
    sessions: list = None,
    rooms: list = None,
    speakers: list = None,
    participants: list = None,
    crisis: dict = None,
) -> SwarmState:
    """Helper to build a clean initial state for any workflow."""
    # Pull sessions/rooms from nested schedule if not provided flat
    _sessions = sessions or (schedule or {}).get("sessions", []) or []
    _rooms = rooms or (schedule or {}).get("rooms", []) or []

    return SwarmState(
        messages=[],
        event_context=event_context or {},
        sessions=_sessions,
        rooms=_rooms,
        speakers=speakers or [],
        schedule_changes=[],
        schedule=schedule,
        participants=participants,
        email_queue=[],
        emails_sent=0,
        social_queue=[],
        generated_posts=[],
        active_crisis=crisis,
        crisis_resolution=None,
        next_agent=workflow_type,   # Entry point matches workflow type
        workflow_complete=False,
        agent_logs=[],
    )


def merge_state(base: SwarmState, update: dict) -> SwarmState:
    """
    Merges a partial agent update dict into the current state.
    For list fields tagged as 'additive', appends rather than replaces.
    """
    additive_fields = {"agent_logs", "messages"}
    new_state = dict(base)
    for key, value in update.items():
        if key in additive_fields and isinstance(value, list):
            new_state[key] = list(new_state.get(key) or []) + value
        else:
            new_state[key] = value
    return SwarmState(**new_state)
